### ISSUE TITLE
Undefined view in contextual links info for core views

### ISSUE THREAD

**Issue by bradbulger** [backdrop-contrib/nodequeue#35]
Running Backdrop 1.17.0 and Nodequeue 2.3.0, I'm getting undefined index errors from several core views like user_admin

Notice: Undefined index: view in nodequeue_contextual_links_view_alter() (line 538 of /path/to/site/modules/contrib/nodequeue/nodequeue.module

The #contextual_links element has view info, but $element['#element']['#views_contextual_links_info']['views_ui'] does not have a View object, only location, view name, and display ID.

That View object was removed in https://github.com/backdrop/backdrop-issues/issues/1155. I couldn't find any other reference to 'nodequeue_nodes_node' but maybe that relationship name is constructed somewhere else?

So I don't know what circumstance the code is supposed to be handling, to see how to do it now.

**Comment by herbdool** [comment]
@bradbulger I got error too. I'm not sure either what the code is doing. I've attempted to load the view and display and see if that fixes it. I'm not convinced it is right. PR https://github.com/backdrop-contrib/nodequeue/pull/38

Maybe there's much less heavy handed approach to the whole thing. Not clear why we'd need the whole views object here.

**Comment by jenlampton** [comment]
The function `nodequeue_contextual_links_view_alter()` is adding a `Configure queue` link into the contextual links for the view, if the view has a relationship to a nodequeue, and if the relationship is limited to a single queue. 

This feature still seems to work for me even without this chunk of code, and since I also don't see any other reference to `nodequeue_nodes_node` I wonder if this is outdated? I'm going to remove it entirely.

**Comment by jenlampton** [comment]
Closing for now, please re-open if the problem persists.

**Comment by herbdool** [comment]
Looks like you wrapped it in an if. Good enough for now. Interested in making a bug release? @jenlampton
