### ISSUE TITLE
Doesn't create automatically one view per queue

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/nodequeue#9]
On *admin/structure/nodequeue/settings*, there is an option to let Nodequeue "Automatically create one view per queue". On my Backdrop 1.6.3 site, the option is enabled.

After creating a queue (and adding some posts to it), there is no Nodequeue view on *admin/structure/views*. When I go to *nodequeue/1* which would be the default path of the first Nodequeue view of a site, I see a "Page not found" message.

**Comment by Al-Rozhkov** [comment]
I can confirm it. Looks like a bug.

**Comment by jenlampton** [comment]
Okay, I've had to rework the way views were added since `hook_views_default_views()` doesn't exist anymore, but I think I've got it doing roughly the same thing as before. I'm going to put this into the next release since it's better than what we had before, but would love some feedback once you guys update :)

**Comment by olafgrabienski** [comment]
Thanks for working on the automatic view creation! Here's some feedback:

After updating Nodequeue to the last version, I added a new queue and still didn't find any nodequeue related view on *admin/structure/views*. The views (including one which related to an older queue) appeared then in the *Views* list after I visited *admin/structure/nodequeue/settings* and disabled and reenabled the "Automatically create one view per queue" option. (There was also the message "Default nodequeue views have been created.")

Seeing the views in the list, I clicked on one of the links (`example.com/nodequeue-2`) but got a *Page not found* message. So I opened the view configuration, checked the Preview option of the view and got the following red message:

```SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') WHERE (( (node.status = 1 OR (node.uid = 1 AND 1 <> 0 AND 1 = 1) OR 1 = 1 OR 1' at line 1```

**Comment by jenlampton** [comment]
Interesting. Can tell me what the SQL query was? 
* go to views settings
* check the box for `Show the SQL query`
* open the view configuration again
* check the Preview option again

**Comment by olafgrabienski** [comment]
@jenlampton Sure, here's the query:	

```
SELECT nodequeue_nodes_node.position AS nodequeue_nodes_node_position, node.nid AS nid
FROM 
{node} node
INNER JOIN {nodequeue_nodes} nodequeue_nodes_node ON node.nid = nodequeue_nodes_node.nid AND nodequeue_nodes_node.qid IN (  )
WHERE (( (node.status = 1 OR (node.uid = 1 AND 1 <> 0 AND 1 = 1) OR 1 = 1 OR 1 = 1) ))
ORDER BY nodequeue_nodes_node_position ASC
LIMIT 10 OFFSET 0
```

Note: First I didn't find the option `Show the SQL query`. It became visible after I checked `Show information and statistics about the view during live preview`.

**Comment by jenlampton** [comment]
Thank you, I see the problem!  Will try to get a fix in asap.

**Comment by b1daly** [comment]
FWIW, there is still an issue with this. Before I saw this issue queue, I wasn't getting the view auto created. I had stopped and started my site (running from Lando), then saw the work around from @olafgrabienski of going to nodequeue/settings and unclicking the "Automatically create one view per queue" then resetting. After that, the view automatically showed up.

I'm not sure anecdotal reports like this are of any use, I only mention it as some feedback from a "real world" non-technical user. I'm trying to migrate our D6 site I built 10 years ago. I had put it off, due to the pain, but finally decided to go with Backdrop.

Overall, I'm making progress, but I've had enough of these simple usability issues that I've almost abandoned for drupal 8. The issue here, our old site heavily used Nodequeue, but when I built it, I relied on the auto created views. I was unaware that the view could be referenced by argument. So it's been the usual hours of head scratching, thinking I must be doing something wrong!

I think Backdrop has a huge opportunity with simple "site builders," because my initial experience with D8, in which to get going I had to start fussing with 3 command line tools (drush, dashboard, composer) blew me out of the water.

This is a really challenging project, and overall I really like the approach you are taking, towards more simplicity, I'm just giving a little feedback. Thanks for a great product!
Brian

**Comment by b1daly** [comment]
just adding, the current way it's working for me, after adding the nodequeue, unsetting and resetting the option to 'automatically create one view per queue' is required for the view to show up

**Comment by jenlampton** [comment]
Thanks for the feedback @b1daly, it sounds like there's still a problem with the "automatic" part of the view creation. I'll have another look!

**Comment by jenlampton** [comment]
Okay - I believe I've got the one view per queue working again. Now when I add a queue I get a view and when I remove a queue that view gets deleted (as long as it has not been overridden). 

I've also got the SQL query error resolved. I'm going to make a new release.

**Comment by olafgrabienski** [comment]
Thanks for the new release! Just tested on a site: added a new queue, the view was created and the views page accessible. Deleted the queue, and the view was deleted. I guess we can close this issue.
